window.QUESTIONS_NL = [
  { c: 'Priority', t: 'K', q: 'Je komt bij een gelijkwaardige kruising. Een auto komt van rechts. Wat moet je doen?', o: ['Snel doorrijden', 'Voorrang geven aan de auto van rechts', 'Claxonneren', 'De auto links heeft altijd voorrang'], a: 1, e: '<strong>Rechts gaat voor</strong> op gelijkwaardige kruisingen, tenzij borden, markeringen of verkeerslichten iets anders aangeven.' },
  { c: 'Priority', t: 'K', q: 'Je rijdt op een voorrangsweg met een geel ruitbord. Een auto komt uit een zijweg. Wie heeft voorrang?', o: ['De auto uit de zijweg', 'Jij, omdat je op een voorrangsweg rijdt', 'Wie het eerst aankomt', 'Niemand'], a: 1, e: 'Een geel ruitbord betekent dat je op een voorrangsweg rijdt. Verkeer uit zijwegen moet voorrang verlenen.' },
  { c: 'Priority', t: 'I', q: 'Een bus geeft binnen de bebouwde kom richting aan om weg te rijden bij een halte. Wat doe je?', o: ['Snel inhalen', 'Voorrang geven als dat veilig kan', 'Claxonneren', 'Altijd direct stoppen midden op de rijbaan'], a: 1, e: 'Binnen de bebouwde kom moet je een bus die bij een halte wil wegrijden voorrang geven, zolang dit veilig kan.' },
  { c: 'Priority', t: 'I', q: 'Je nadert een rotonde met haaientanden bij de ingang. Wie heeft meestal voorrang?', o: ['Jij als oprijdend verkeer', 'Verkeer op de rotonde', 'De auto rechts', 'De grootste auto'], a: 1, e: 'Haaientanden betekenen dat je voorrang moet verlenen. Op veel rotondes heeft verkeer op de rotonde voorrang.' },
  { c: 'Priority', t: 'I', q: 'Je slaat linksaf en een fietser rijdt rechtdoor op dezelfde weg. Wie gaat voor?', o: ['Jij, omdat je richting aangeeft', 'De fietser die rechtdoor gaat', 'Wie het snelst rijdt', 'Auto’s gaan altijd voor'], a: 1, e: 'Verkeer dat rechtdoor gaat op dezelfde weg gaat normaal vóór afslaand verkeer.' },
  { c: 'Priority', t: 'I', q: 'Een voetganger staat duidelijk klaar bij een zebrapad. Wat moet je doen?', o: ['Doorrijden', 'Voorrang geven en kunnen stoppen', 'Claxonneren', 'Alleen remmen als de voetganger al loopt'], a: 1, e: 'Bij een zebrapad moet je voetgangers die oversteken of duidelijk willen oversteken voorrang geven.' },
  { c: 'Priority', t: 'I', q: 'Je verlaat een parkeerplaats en wilt de rijbaan oprijden. Wie heeft voorrang?', o: ['Jij', 'Verkeer op de rijbaan', 'Alleen fietsers', 'Niemand'], a: 1, e: 'Wegrijden uit een parkeervak is een bijzondere manoeuvre. Je moet ander verkeer voor laten gaan.' },
  { c: 'Priority', t: 'K', q: 'Een verkeersregelaar geeft een aanwijzing die afwijkt van het verkeerslicht. Wat volg je?', o: ['Het verkeerslicht', 'De aanwijzing van de verkeersregelaar', 'Alleen de wegmarkering', 'De auto rechts'], a: 1, e: 'Aanwijzingen van bevoegde verkeersregelaars gaan boven verkeerslichten en borden.' },

  { c: 'Speed limits', t: 'K', q: 'Wat is de standaard maximumsnelheid binnen de bebouwde kom als er geen bord staat?', o: ['30 km/u', '50 km/u', '60 km/u', '80 km/u'], a: 1, e: 'Binnen de bebouwde kom geldt meestal 50 km/u, tenzij borden iets anders aangeven.' },
  { c: 'Speed limits', t: 'K', q: 'Wat is de algemene maximumsnelheid voor personenauto’s op de autosnelweg als er geen lagere limiet staat?', o: ['100 km/u', '120 km/u', '130 km/u', '90 km/u'], a: 2, e: 'De algemene maximumsnelheid is 130 km/u, maar vaak gelden lagere of tijdgebonden limieten. Volg altijd de borden.' },
  { c: 'Speed limits', t: 'K', q: 'Wat is de standaard maximumsnelheid buiten de bebouwde kom op een gewone weg?', o: ['60 km/u', '80 km/u', '100 km/u', '120 km/u'], a: 1, e: 'Op gewone wegen buiten de bebouwde kom geldt meestal 80 km/u, tenzij anders aangegeven.' },
  { c: 'Speed limits', t: 'K', q: 'Je rijdt een 30 km/u-zone binnen. Tot waar geldt deze snelheid?', o: ['Tot de volgende kruising', 'Tot het einde-zonebord', 'Slechts 300 meter', 'Alleen bij scholen'], a: 1, e: 'Een zonebord geldt tot het bijbehorende einde-zonebord.' },
  { c: 'Speed limits', t: 'I', q: 'Het is mistig en de limiet is 80 km/u. Wat is veilig?', o: ['Altijd 80 rijden', 'Snelheid aanpassen aan zicht en omstandigheden', 'Groot licht aan en 80 rijden', 'Dicht achter je voorganger rijden'], a: 1, e: 'De maximumsnelheid is niet altijd een veilige snelheid. Pas je snelheid aan de omstandigheden aan.' },
  { c: 'Speed limits', t: 'K', q: 'Een matrixbord boven jouw rijstrook toont 70. Wat betekent dat?', o: ['Alleen advies', 'Maximumsnelheid voor die rijstrook', 'Minimumsnelheid', 'Limiet begint pas later'], a: 1, e: 'Matrixborden kunnen verplichte snelheidslimieten per rijstrook aangeven.' },

  { c: 'Traffic signs', t: 'K', q: 'Een blauw rond bord met een witte pijl omhoog betekent wat?', o: ['Adviesrichting', 'Verboden in te rijden', 'Verplicht rechtdoor', 'Einde eenrichtingsweg'], a: 2, e: 'Blauwe ronde borden geven een verplichting aan. Een pijl omhoog betekent verplicht rechtdoor.' },
  { c: 'Traffic signs', t: 'K', q: 'Een omgekeerde driehoek met rode rand betekent wat?', o: ['Stoppen', 'Voorrang verlenen', 'Verboden toegang', 'Je hebt voorrang'], a: 1, e: 'De omgekeerde driehoek is het bord voor voorrang verlenen.' },
  { c: 'Traffic signs', t: 'K', q: 'Een rond rood bord met een witte horizontale balk betekent wat?', o: ['Maximumsnelheid', 'Verboden in te rijden', 'Parkeerverbod', 'Inhaalverbod'], a: 1, e: 'Dit bord betekent verboden in te rijden vanuit deze richting.' },
  { c: 'Traffic signs', t: 'K', q: 'Wat betekent het woord “Erf” op een verkeersbord?', o: ['30 km/u-zone', 'Woonerf: stapvoets rijden en parkeren alleen waar toegestaan', 'Fietsers verboden', 'Vrij parkeren'], a: 1, e: 'In een erf moet je stapvoets rijden, rekening houden met voetgangers en alleen parkeren waar dat mag.' },
  { c: 'Traffic signs', t: 'K', q: 'Wat betekenen haaientanden op de weg?', o: ['Je hebt voorrang', 'Je moet voorrang verlenen', 'Je moet tien seconden stoppen', 'Fietsers zijn verboden'], a: 1, e: 'Haaientanden geven aan dat je voorrang moet verlenen.' },
  { c: 'Traffic signs', t: 'K', q: 'Een stopbord betekent wat?', o: ['Alleen afremmen', 'Volledig stoppen en waar nodig voorrang verlenen', 'Alleen ’s nachts stoppen', 'Alleen stoppen voor fietsers'], a: 1, e: 'Bij een stopbord moet je volledig stoppen en daarna voorrang verlenen volgens de situatie.' },
  { c: 'Traffic signs', t: 'K', q: 'Een blauw rechthoekig bord met een witte P betekent wat?', o: ['Betaald parkeren', 'Parkeren toegestaan', 'Privéterrein', 'Alleen invaliden'], a: 1, e: 'Een witte P op blauw betekent parkeren toegestaan. Onderborden kunnen beperkingen aangeven.' },

  { c: 'Alcohol & drugs', t: 'K', q: 'Wat is de wettelijke alcohollimiet in het bloed voor een ervaren bestuurder?', o: ['0,0‰', '0,2‰', '0,5‰', '0,8‰'], a: 2, e: 'Voor ervaren bestuurders wordt meestal 0,5‰ als limiet genoemd. De veiligste keuze is niet drinken als je rijdt.' },
  { c: 'Alcohol & drugs', t: 'K', q: 'Wat is de alcohollimiet voor een beginnende bestuurder?', o: ['0,0‰', '0,2‰', '0,5‰', '0,8‰'], a: 1, e: 'Voor beginnende bestuurders geldt een lagere limiet: meestal 0,2‰.' },
  { c: 'Alcohol & drugs', t: 'K', q: 'Op je medicijn staat dat het de rijvaardigheid kan beïnvloeden. Wat doe je?', o: ['Alleen korte ritten maken', 'Een lagere dosis nemen', 'Niet rijden totdat arts of apotheker zegt dat het veilig is', 'Langzamer rijden'], a: 2, e: 'Bij medicijnen die de rijvaardigheid kunnen beïnvloeden moet je advies vragen aan arts of apotheker.' },
  { c: 'Alcohol & drugs', t: 'K', q: 'Waarom is rijden onder invloed van drugs gevaarlijk?', o: ['Alleen omdat het duur is', 'Reactie, oordeel en controle kunnen slechter worden', 'Het beïnvloedt alleen zicht', 'Het is veilig als je langzaam rijdt'], a: 1, e: 'Drugs kunnen reactietijd, aandacht, oordeel en voertuigcontrole verminderen.' },

  { c: 'Overtaking', t: 'K', q: 'Wanneer mag je op de autosnelweg normaal rechts inhalen?', o: ['Altijd als links langzaam rijdt', 'Normaal niet; alleen in specifieke situaties', 'Altijd bij vrachtwagens', 'Alleen als je claxonneert'], a: 1, e: 'Inhalen gebeurt normaal links. Rechts passeren mag alleen in specifieke situaties, zoals fileverkeer of bijzondere rijstrookindeling.' },
  { c: 'Overtaking', t: 'I', q: 'Wat moet je zeker weten voordat je inhaalt op een tweebaansweg?', o: ['Alleen dat je spiegels hebt bekeken', 'Dat je de manoeuvre veilig kunt afronden zonder anderen te hinderen', 'Dat de voorganger onder de limiet rijdt', 'Dat er geen fietsers zijn'], a: 1, e: 'Haal alleen in als zicht, afstand en ruimte voldoende zijn om veilig af te ronden.' },
  { c: 'Overtaking', t: 'K', q: 'Wat is een veilige afstand bij het passeren van een fietser met hogere snelheid?', o: ['Zo dicht mogelijk', 'Ruime zijdelingse afstand, ongeveer 1,5 meter of meer als dat kan', 'Alleen claxonneren', 'Dichterbij rijden om sneller voorbij te zijn'], a: 1, e: 'Houd ruime zijdelingse afstand bij fietsers. Bij hogere snelheid is ongeveer 1,5 meter of meer een veilige vuistregel.' },
  { c: 'Overtaking', t: 'I', q: 'Je wordt ingehaald. Wat doe je?', o: ['Versnellen', 'Gelijkmatig blijven rijden en de manoeuvre niet moeilijker maken', 'Plots naar links sturen', 'Hard remmen'], a: 1, e: 'Als je wordt ingehaald, blijf voorspelbaar en hinder de ander niet.' },

  { c: 'Motorway', t: 'K', q: 'Je voegt in op de autosnelweg. Wie heeft voorrang?', o: ['Jij op de invoegstrook', 'Verkeer dat al op de autosnelweg rijdt', 'Wie het eerst bij het punt is', 'Zware voertuigen'], a: 1, e: 'Verkeer op de autosnelweg heeft voorrang. Gebruik de invoegstrook om veilig snelheid te maken en in te voegen.' },
  { c: 'Motorway', t: 'I', q: 'Je mist je afrit op de autosnelweg. Wat doe je?', o: ['Achteruitrijden op de vluchtstrook', 'Doorrijden naar de volgende afrit', 'Stoppen en keren', 'Via de vluchtstrook terugrijden'], a: 1, e: 'Nooit achteruitrijden of keren op de autosnelweg. Rijd veilig door naar de volgende afrit.' },
  { c: 'Motorway', t: 'K', q: 'Waarvoor is de vluchtstrook vooral bedoeld?', o: ['Normaal rijden bij drukte', 'Noodstop of pech', 'Inhalen', 'Telefoneren'], a: 1, e: 'De vluchtstrook is voor noodgevallen en pech, tenzij borden tijdelijk iets anders aangeven.' },
  { c: 'Motorway', t: 'I', q: 'Een rood kruis staat boven een rijstrook. Wat moet je doen?', o: ['Die rijstrook kort gebruiken', 'Die rijstrook verlaten en niet gebruiken', 'Sneller doorrijden', 'Stoppen onder het bord'], a: 1, e: 'Een rood kruis boven een rijstrook betekent dat deze gesloten is.' },
  { c: 'Motorway', t: 'K', q: 'Wat is een veilige volgafstand bij droge omstandigheden?', o: ['Minimaal twee seconden', 'Altijd exact drie seconden wettelijk verplicht', 'Altijd 50 meter', 'Één seconde'], a: 0, e: 'Een veelgebruikte veiligheidsregel is minstens twee seconden afstand, meer bij regen, donkerte of slecht zicht.' },

  { c: 'Lights', t: 'K', q: 'Wanneer gebruik je overdag dimlicht?', o: ['Alleen in tunnels', 'Bij verminderd zicht, zoals regen, mist, sneeuw of schemer', 'Alleen ’s nachts', 'Alleen op de snelweg'], a: 1, e: 'Gebruik dimlicht bij verminderd zicht. Dagrijverlichting is niet altijd voldoende.' },
  { c: 'Lights', t: 'K', q: 'Wanneer mag je mistachterlicht gebruiken?', o: ['Altijd bij regen', 'Alleen bij zeer slecht zicht, meestal minder dan ongeveer 50 meter', 'Altijd in het donker', 'Als je je veiliger voelt'], a: 1, e: 'Mistachterlicht is bedoeld voor zeer slecht zicht en kan achterliggers verblinden als je het verkeerd gebruikt.' },
  { c: 'Lights', t: 'K', q: 'Waarom is groot licht in mist vaak verkeerd?', o: ['Het kan terugkaatsen en het zicht verminderen', 'Het maakt de auto langzamer', 'Het zet de motor uit', 'Het is alleen voor fietsen'], a: 0, e: 'Groot licht kan door mist terugkaatsen en je zicht slechter maken.' },
  { c: 'Lights', t: 'K', q: 'Wanneer gebruik je alarmlichten?', o: ['Om overal te parkeren', 'Om anderen te waarschuwen voor gevaar of pech', 'Bij hard rijden', 'Om iemand te bedanken'], a: 1, e: 'Alarmlichten gebruik je om andere weggebruikers te waarschuwen voor gevaar, pech of een obstakel.' },

  { c: 'Vehicle & docs', t: 'K', q: 'Wat is een APK?', o: ['Een rijbewijscategorie', 'De verplichte periodieke keuring van het voertuig', 'Een tolbetaling', 'Een verzekering'], a: 1, e: 'APK is de periodieke keuring van voertuigen op verkeersveiligheid en milieu.' },
  { c: 'Vehicle & docs', t: 'K', q: 'Je bandenprofiel is onder de wettelijke limiet. Wat moet je doen?', o: ['Alleen voorzichtig rijden', 'Banden vervangen voordat je de openbare weg op gaat', '20 km/u langzamer rijden', 'Alleen bij droog weer rijden'], a: 1, e: 'Banden onder de wettelijke profieldiepte zijn onveilig en moeten worden vervangen.' },
  { c: 'Vehicle & docs', t: 'K', q: 'Waarom moet je bandenspanning regelmatig controleren?', o: ['Het beïnvloedt veiligheid, remmen, brandstofverbruik en slijtage', 'Het verandert de kleur van de auto', 'Het geldt alleen voor vrachtwagens', 'Het vervangt verzekering'], a: 0, e: 'Juiste bandenspanning helpt grip, remmen, stabiliteit, brandstofverbruik en levensduur van banden.' },
  { c: 'Vehicle & docs', t: 'K', q: 'Een rood waarschuwingslampje brandt tijdens het rijden. Wat doe je meestal?', o: ['Negeren', 'Veilig stoppen en volgens het instructieboekje controleren', 'Sneller rijden', 'Alle verlichting uitzetten'], a: 1, e: 'Rode waarschuwingslampjes duiden meestal op een urgent probleem. Stop veilig en controleer.' },

  { c: 'Parking', t: 'K', q: 'Een doorgetrokken gele streep langs de stoeprand betekent meestal wat?', o: ['Parkeren aanbevolen', 'Stilstaan verboden', 'Alleen vrachtwagens mogen stoppen', 'Kort stoppen mag altijd'], a: 1, e: 'Een doorgetrokken gele streep betekent meestal dat stilstaan verboden is.' },
  { c: 'Parking', t: 'I', q: 'Je wilt kort stoppen waar stilstaan verboden is. Mag dat om iemand uit te laten?', o: ['Ja, kort stoppen mag altijd', 'Nee, waar stilstaan verboden is mag je niet stoppen', 'Ja, als je in de auto blijft', 'Alleen als er geen bus is'], a: 1, e: 'Als stilstaan verboden is, mag je ook niet kort stoppen om iemand uit te laten.' },
  { c: 'Parking', t: 'K', q: 'Wie mag parkeren op een plek met rolstoelsymbool?', o: ['Iedereen kort', 'Alleen bevoegde houders van een gehandicaptenparkeerkaart', 'Alleen elektrische auto’s', 'Alleen motoren'], a: 1, e: 'Gehandicaptenparkeerplaatsen zijn gereserveerd voor bevoegde vergunninghouders.' },
  { c: 'Parking', t: 'K', q: 'Wat is het doel van een parkeerschijfzone?', o: ['Parkeerduur beperken tijdens aangegeven tijden', 'Onbeperkt parkeren', 'Alle voertuigen verbieden', 'Een busbaan markeren'], a: 0, e: 'In een parkeerschijfzone mag je parkeren onder de tijdsbeperkingen die op de borden staan.' },

  { c: 'Cyclists & pedestrians', t: 'I', q: 'Een kind op de fiets slingert voor je. Wat doe je?', o: ['Snel passeren', 'Extra afstand houden en snelheid verminderen', 'Claxonneren', 'Met groot licht seinen'], a: 1, e: 'Kinderen kunnen onverwacht bewegen. Verminder snelheid en geef extra ruimte.' },
  { c: 'Cyclists & pedestrians', t: 'I', q: 'Je slaat rechtsaf over een fietspad. Wat moet je controleren?', o: ['Spiegels en dode hoek op fietsers of bromfietsers', 'Alleen het verkeerslicht', 'Alleen je snelheid', 'Niets als je richting aangeeft'], a: 0, e: 'Controleer altijd spiegels en dode hoek voordat je een fietspad kruist.' },
  { c: 'Cyclists & pedestrians', t: 'I', q: 'Er is te weinig ruimte om een fietser veilig in te halen. Wat doe je?', o: ['Wachten tot veilig passeren mogelijk is', 'Erdoorheen persen', 'Lang claxonneren', 'Over de stoep rijden'], a: 0, e: 'Als er onvoldoende ruimte is, wacht je totdat je veilig kunt passeren.' },
  { c: 'Cyclists & pedestrians', t: 'I', q: 'Een voetganger kijkt op zijn telefoon bij een oversteekplaats. Wat is veilig?', o: ['Aannemen dat hij jou ziet', 'Snelheid verminderen en rekening houden met onverwacht oversteken', 'Dichterbij rijden', 'Alleen groot licht gebruiken'], a: 1, e: 'Afgeleide voetgangers kunnen onverwacht oversteken. Verminder snelheid en wees voorbereid.' },

  { c: 'Insight', t: 'I', q: 'Een bal rolt tussen geparkeerde auto’s de weg op. Wat verwacht je?', o: ['Er kan een kind achteraan komen', 'Er gebeurt niets', 'Alleen fietsers stoppen', 'De bal heeft voorrang'], a: 0, e: 'Een bal op de weg kan betekenen dat er een kind in de buurt is. Rem af en wees klaar om te stoppen.' },
  { c: 'Insight', t: 'I', q: 'Een geparkeerde bestelbus blokkeert je zicht bij een kruising. Wat doe je?', o: ['Versnellen', 'Langzaam naderen en voorzichtig kijken', 'Claxonneren en doorrijden', 'Doorrijden omdat links moet wachten'], a: 1, e: 'Bij beperkt zicht moet je langzaam en voorzichtig observeren voordat je oprijdt.' },
  { c: 'Insight', t: 'I', q: 'Het regent hard en je voorganger veroorzaakt opspattend water. Wat is veilig?', o: ['Afstand houden zoals normaal', 'Meer afstand houden en snelheid verminderen', 'Inhalen', 'Hard remmen met alarmlichten'], a: 1, e: 'Regen vergroot de remweg en vermindert zicht. Houd meer afstand en verminder snelheid.' },
  { c: 'Insight', t: 'I', q: 'Je bent moe na een lange dag. Wat is het veiligst?', o: ['Pauze nemen of niet rijden', 'Raam open en doorrijden', 'Sneller rijden', 'Harde muziek aanzetten'], a: 0, e: 'Vermoeidheid vermindert reactie en oordeel. Rust nemen is de veiligste keuze.' },
  { c: 'Insight', t: 'I', q: 'De zon staat laag en schijnt in je ogen. Wat doe je?', o: ['Snelheid verminderen, afstand vergroten en zonneklep/zonnebril gebruiken', 'Sneller rijden', 'Ogen even sluiten', 'Mistachterlicht aanzetten'], a: 0, e: 'Verblinding vermindert je zicht. Verminder snelheid en vergroot afstand.' },

  { c: 'Emergency', t: 'K', q: 'Je ziet blauwe zwaailichten en hoort een sirene achter je. Wat doe je?', o: ['Direct stoppen waar je bent', 'Veilig en snel ruimte maken', 'Versnellen', 'Gewoon doorrijden'], a: 1, e: 'Maak ruimte voor hulpdiensten zonder nieuw gevaar te veroorzaken.' },
  { c: 'Emergency', t: 'K', q: 'Na een kleine aanrijding, wat is je eerste prioriteit?', o: ['Veiligheid van mensen en verder gevaar voorkomen', 'Eerst foto’s maken', 'Meteen wegrijden', 'Alle voertuigen verplaatsen zonder te kijken'], a: 0, e: 'Zorg eerst voor veiligheid, controleer op letsel en voorkom extra gevaar.' },
  { c: 'Emergency', t: 'I', q: 'Je motor raakt oververhit. Wat doe je?', o: ['Veilig stoppen en niet doorrijden bij een ernstige waarschuwing', 'Sneller rijden', 'Negeren', 'Brandstofdop openen'], a: 0, e: 'Een oververhitte motor kan schade of gevaar veroorzaken. Stop veilig en controleer.' },
  { c: 'Emergency', t: 'I', q: 'Een voertuig voor je verliest lading op de weg. Wat doe je?', o: ['Hard remmen zonder te kijken', 'Veilig vertragen, afstand houden en zo nodig waarschuwen', 'Er hard overheen rijden', 'In de rijstrook stoppen om het op te pakken'], a: 1, e: 'Losse lading is gevaarlijk. Houd afstand en reageer rustig om een tweede ongeval te voorkomen.' },

  { c: 'Environment', t: 'K', q: 'Welke rijstijl bespaart brandstof en vermindert uitstoot?', o: ['Hoge toeren in lage versnelling', 'Vooruitkijken, soepel accelereren en hard remmen vermijden', 'Altijd maximaal optrekken', 'Altijd airco gebruiken'], a: 1, e: 'Anticiperend en soepel rijden is veiliger en zuiniger.' },
  { c: 'Environment', t: 'K', q: 'Wat controleer je minimaal voor een lange snelwegrit?', o: ['Alleen brandstof', 'Bandenspanning, olie, koelvloeistof en ruitensproeiervloeistof', 'Alleen banden', 'Niets'], a: 1, e: 'Bandenspanning en vloeistoffen beïnvloeden veiligheid en betrouwbaarheid.' },
  { c: 'Environment', t: 'I', q: 'Je wacht enkele minuten op iemand. Wat is milieubewuster?', o: ['Motor uitzetten als dat veilig en passend is', 'Motor stationair laten draaien', 'Af en toe gas geven', 'Groot licht aanzetten'], a: 0, e: 'Onnodig stationair draaien vermijden vermindert uitstoot en brandstofverbruik.' },
  { c: 'Environment', t: 'K', q: 'Waarom verwijder je onnodige dakdragers of zware spullen?', o: ['Ze kunnen brandstofverbruik verhogen', 'Ze verbeteren altijd de wegligging', 'Ze verminderen altijd bandenslijtage', 'Ze zijn verplicht'], a: 0, e: 'Extra gewicht en luchtweerstand kunnen het brandstofverbruik verhogen.' }
];
window.EXTRA_QUESTIONS_NL = [];
